version: '3.1'
services:
  fookie:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks: #here
      - my-network
  mongo:
    image: mongo
    ports:
        - 27017:27017
    networks: #here
      - my-network 
  grafana:
    image: grafana/grafana
    ports:
      - '5000:3000'
  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - '9090:9090'    
    networks:
      - my-network 
networks:
  my-network:
    driver: bridge