version: '3.1'
services:
  fookie:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
        - 27017:27017
  grafana:
    image: grafana/grafana
    ports:
      - '5000:3000'
  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - '9090:9090'
    volumes: 
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  postgre:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123

